language: php
sudo: false

cache:
    directories:
      - $HOME/.composer/cache

php: 
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

allow_failures:
  - php: 7.0

before_script:
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then cp phpspec_coverage.yml phpspec.yml; fi;'
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then composer require --dev  henrikbjorn/phpspec-code-coverage "~0.2"; fi;'
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then composer update; fi;'

after_script:
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi;'
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.xml; fi;'

script: vendor/bin/phpspec run --format=dot