language: php

php: 
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    php: hhvm

before_script:
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then cp phpspec_coverage.yml phpspec.yml; fi;'
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then composer require --no-update --dev  henrikbjorn/phpspec-code-coverage "~0.2"; fi;'
  - composer install
after_script:
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi;'
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.xml; fi;'

script: vendor/bin/phpspec run